---
always_allow_html: true
output:
  pdf_document:
    keep_tex: true
    toc: true
    toc_depth: 1
    template: ../latex/template.tex
    pandoc_args: ["--top-level-division=chapter"]

date: "`r format(Sys.time(), '%Y')`"
author: |
  | Douglas Martins Mendes Braga
  | Felipe de Carvalho Salles
orientador: Gustavo Henrique Mitraud Assis Rocha
detorientador: Orientador - ENCE/IBGE

leitor: Cassio Freitas Pereira de Almeida
detleitor: ENCE/IBGE

instituicao: |
  Instituto Brasileiro de Geografia e Estatística - IBGE
  
  Escola Nacional de Ciências Estatísticas - ENCE
  
  Bacharelado em Estatística

title: "Precificação da diária de propriedades da plataforma Airbnb na cidade do Rio de Janeiro"

resumo: |
  A acomodação em um estabelecimento de hospedagem pode abranger uma gama de inúmeros elementos, tais como limpeza, recepção, localização, preço e outros. Como cada item não é comercializado separadamente no mercado, torna-se mais complexo saber o real valor que cada um entrega ao consumidor. Com isso, a forma de pensar e agir na definição do preço da diária desses empreendimentos pode ter enfoque em diversas variáveis. Esta pesquisa teve como objetivo comparar métodos de custeio do preço de diária do site Airbnb, dos estabelecimentos localizados na cidade do Rio de Janeiro, bem como os fatores levados em conta na formação do preço, a fim de que o usuário possa verificar se há um preço justo na locação do estabelecimento. A estimação dos preços foi realizada por meio de aprendizado de máquina, com uma breve comparação a um modelo de regressão linear.
keywords: Machine Learning. Precificação. Hospedagem
agradecimento: |
  Agradecemos aos nossos familiares que nos apoiaram até aqui e que foram a nossa fonte de inspiração. Somos gratos aos colegas de turma que lutaram junto conosco todos os dias. Aos amigos que nunca negaram palavras de força, incentivo e otimismo ao longo da jornada acadêmica. Aos nossos mestres que acompanharam toda a nossa trajetória dentro do curso de estatística. Ao nosso orientador Gustavo Rocha que foi incansável em suas orientações, pesquisas e revisões. Nosso muito obrigado à Escola Nacional de Ciências Estatísticas\footnote{\url{http://www.ence.ibge.gov.br/}} por nos proporcionar o melhor ambiente educacional.

preambulo: |
  Monografia apresentada à Escola 
  Nacional de Ciências Estatísticas do 
  Instituto Brasileiro de Geografia e 
  Estatística como requisito parcial à 
  obtenção do título de Bacharel em 
  Estatística.

bibliography: ../latex/bibliography.bibtex
csl: ../latex/associacao-brasileira-de-normas-tecnicas-ipea.csl
link-citations: true
---

```{r setup, include=FALSE}
require(magrittr)
require(knitr)

opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
download.file(
  "https://imgur.com/download/Qn0qJdv/",
  "../fig/ence.png", quiet = T, mode = 'wb')
```

```{r child='01-introducao.rmd'}
```

```{r child='02-revisao.rmd'}
```

```{r child='03-dados.rmd'}
```

```{r child='04.0-metodologia.rmd'}
```

```{r child='05-resultados.rmd'}
```

\newpage

# REFERÊNCIAS {.unnumbered}

<div id="refs"></div>


# APÊNDICE A {.unnumbered}

