# Revisão Bibliográfica

Um novo movimento, chamado de *economia compartilhada*, apareceu há pouco tempo como uma opção para atender necessidades diversas, que, anteriormente, eram satisfeitas dominantemente por empresas. Os clientes passaram a querer ter acesso a produtos e a pagar pela experiência de tê-los momentaneamente, ao invés de adquiri-los por definitivo [@eckhardt2015sharing].

Segundo @belk2014you, a economia compartilhada é o resultado da progressão tecnológica e socioeconômica. O rápido desenvolvimento da tecnologia com relação à informação e comunicação, tanto por parte de hardwares (como por exemplo, smartphones e tablets) quanto softwares (como por exemplo, aplicativos), concedeu aos usuários promover seu próprio conteúdo, compartilhar informações, colaborar e realizar transações por meio de plataformas [@kaplan2010users].

Logo, a economia compartilhada baseada em diversos modelos de negócios foram rapidamente adotados em várias áreas, como aluguel de ativos próprios (Airbnb.com para acomodações e Moobie.com.br para carros), trabalho autônomo de forma provisória (por exemplo, Fiverr.com), entre outros [@sundararajan2014peer]. @lavaquial2015cocriando acrescenta ainda que esta nova modalidade de negócios conecta a oferta com a demanda, sem necessidade de intermediário, sendo a tecnologia um dos fatores impulsionadores e característicos de práticas colaborativas.

A diversidade de sites para aluguel de acomodações, considerando a economia compartilhada, experimentou um crescimento fenomenal devido à alta demanda turística [@guttentag2015airbnb; @heo2016sharing; @karlsson2016someone; @tussyadiah2016strategic]. Esse tipo de hospedagem é oferecido nos mercados digitais (por exemplo, Airbnb.com e HomeAway.com) por pessoas que possuem o direito de usar o espaço fornecido [@guttentag2015airbnb; @heo2016sharing]. 

Há a possibilidade de acesso a serviços mais baratos e, não por isso, menos qualificados que o hotel, porém de forma privada, representando um novo modo de relação interpessoal [@botsman2010s]. Turistas relatam diversos benefícios na hospedagem no modelo de economia compartilhada, como benefício principal a redução de custos, além da oportunidade de intercâmbio e interação social com seus anfitriões (que podem ser residentes locais) [@balck2015empirical; @guttentag2015airbnb; @quinby2014share]. Sendo assim, a suposição que temos é que o preço é considerado um dos fatores mais relevantes para o consumidor para o uso destas plataformas.

Airbnb, “um dos maiores mercados do mundo para estadias e atividades únicas e autênticas”\footnote{\url{https://news.airbnb.com/br/about-us/}}, é a plataforma líder para o modelo de negócios de hospedagem da economia compartilhada. Fundado em 2008 por Brian Chesky e Joe Gebbia, o Airbnb.com oferece mais de sete milhões de acomodações em mais de 220 países e regiões.

A literatura sobre preço é bastante diversificada. Para @woodruff1997customer, o conceito de valor dá-se exclusivamente à definição pelo cliente, sobre as preferências e as avaliações das características do produto, do desempenho dessas particularidades e das consequências originadas pelo uso, enquanto que para @horngren2008contabilidade, a oferta e procura ditam a definição do preço de um produto ou serviço. As três influências que incidem sobre “oferta e procura” são: os custos, os concorrentes e os clientes. Os clientes influenciam a formação dos preços na medida em que analisam o valor cobrado pelo bem ou serviço e os benefícios que poderão vir a ter se adquiri-los. Os consumidores consideram suas preferências em termos dos benefícios recebidos pelo preço pago. Dessa forma, serviços e bens semelhantes tendem a ter preços semelhantes.

Para @kotler2007principios, no final das contas, é o consumidor quem irá decidir se o preço de um produto está correto. Em todo caso, o melhor não é cobrar preços mais baixos, mas diferenciar o produto ofertado para que ele valha um preço mais alto, de acordo com suas características. Segundo @baker2005administraccao, o preço está fortemente relacionado ao volume de vendas e atuação no mercado, desempenhando uma forte motivação à demanda.

Com relação ao preço de se hospedar em algum tipo de acomodação do Airbnb, há alguns estudos na literatura que mostram, por exemplo, que propriedades com melhores avaliações cobrarem preços mais altos [@gutt2015sharing; @ikkala2014defining]. Para @tang2015neighborhood há uma interação entre localização e preço, relacionada a uma pesquisa com base em propriedades no Airbnb de São Francisco.

Esses estudos iniciaram um interesse em examinar os fatores que determinam o preço da diária baseada na economia compartilhada na cidade do Rio de Janeiro, com objetivo na predição do mesmo. Na formação dos preços de serviços há vários métodos e estratégias que podem ser empregados ligados às condições do mercado, avaliações, às necessidades dos consumidores, a concorrência, características do imóvel, aos custos e ao retorno esperado. Para não ter sua empresa fora do mercado, o gestor deve conceber uma boa ferramenta para a definição do preço.

Nesse sentido, na sequência faz-se um modelo baseado em aprendizado de máquina e outro baseado em uma regressão linear, sobre a formação de preços com base em: custos, localização, índices, valor percebido, entre outros, de modo que o consumidor possa analisar serviços similares e/ou substitutos, e identificar a percepção de valor dos clientes em relação a hospedagem oferecida. Isso auxiliará na definição de preço justo. Com isso, faremos a comparação do desempenho preditivo de um modelo de regressão mais simples com o modelo de aprendizado de máquina e verificar o quanto é necessário um modelo mais complexo.

