# Revisão Bibliográfica

O tema da criminalidade juvenil desperta diverso setores da sociedade para a reflexão da origem e a correta intervenção para o problema. O interesse pelo tema surde devido ao alto índice de mortalidade juvenil no envolvimento com a criminalidade. O Mapa da Violência no Brasil (Waiselfisz, 2016), conhecido como a “anatomia dos homicídios” no Brasil, confirma esses dados. Na faixa de 15 a 29 anos de idade, o crescimento da letalidade violenta foi bem mais intenso comparada ao resto da população. Enquanto na população, o número de Homicídios por Arma de Fogo passou de 6.104, em 1980, para 42.291, em 2014 (crescimento de 592,8%), na faixa jovem, este crescimento foi bem maior: passando de 3.159, em 1980, para 25.255, em 2014 (crescimento de 699,5%).

Para a maioria dos adolescentes, a apresentação de comportamentos de risco, incluindo o cometimento de algum ato infracional, é parte de um processo que se segue como regra (Mun, Windle, & Schainker, 2008; Siegel & Welsh, 2011). Para um subgrupo, entretanto, tais comportamentos, devido à sua persistência e gravidade, indicam uma problemática no plano do desenvolvimento psicossocial (Bazon, Komatsu, Panosso, & Estevão, 2011; Le Blanc, 2003). Entender o processo desenvolvimental que resulta em um padrão de comportamento envolvendo a prática persistente de atos infracionais na adolescência não é uma tarefa simples, mas é indispensável à proposição de políticas públicas, projetos, programas de prevenção em meio a indivíduos considerados vulneráveis, bem como àqueles que já apresentam o problema, para evitar o seu agravamento ou reincidência, já que a política de atendimento dos direitos da criança e do adolescente far-se-á através de um conjunto articulado de ações governamentais e não governamentais, da União, dos estados, do Distrito Federal e dos municípios. - ECA (Brasil, 1990).
