## Aprendizado Supervisionado

O problema de aprendizado supervisionado existe um conjunto de variáveis de entrada que também pode ser chamada de variáveis independentes. Este conjunto de variáveis possui alguma influência em uma ou mais variáveis que podem ser chamadas de variáveis dependentes ou variáveis resposta. Esse problema é conhecido como aprendizado supervisionado e tem como objetivo utilizar as variáveis de entrada para prever as variáveis de saída.^[@friedman2001elements]

### Árvore de decisão

Modelos baseados em árvores de decisão são modelos baseados em uma ou mais regras aninhadas no formato *se-então* para que seja feito o particionamento dos dados, ou seja, prever o resultado.^[@kuhn2013applied]

```
if variável A >= 1.7 then
|  if variável B >= 202.1 then Variável Resposta = 1.3
|  else Variável Resposta = 5.6
else Variável Resposta = 2.5
```

### Métodos *Ensemble*

Muitos pesquisadores buscam maneiras de combinar a previsão de diversos modelos para criar um único modelo que possua uma taxa de acertos maior.^[@opitz1999popular] Os dois principais algoritmos atendem esse objetivo são: *bootstrap aggregating*^[@breiman1996bagging] e *boosting*^[@schapire1999brief]. Ambos algoritmos partem de um modelo base e a escolha deste modelo não é restritiva, pode-se utilizar modelos de regressão logistica^[@friedman2000additive], árvores de decisão, redes neurais^[@martinez2019sequential], entre outros.

#### Bootstrap Aggregating

O algoritmo *Bootstrap Aggregating* também é conhecido como *bagging*

O Random Forest é um algoritmo de Machine Learning amplamente utilizado e que tem como base o *bootstrap aggregating* como o bagging também é conhecido.^[@breiman2001random]

#### Boosting

A técnica conhecida como *boosting* foi introduzida por Schapire, Robert E.^[@schapire1990strength] e tem como objetivo juntar diversos modelos fracos usando combinação aditiva ponderada para criar um modelo forte. 

O ponto principal que diferencia do *bagging* é que este algoritmo é um método sequencial, onde "o modelo aprende com seus erros".


$$

$$




$$
H(x) = \sum_{t=1}^T{\alpha_th_t(\boldsymbol{x})}
$$

### Avaliação de Modelos

#### Validação Cruzada
