version: '3.3'
services:
    shiny:
        build:
            context: .
            dockerfile: shiny_tcc.dockerfile
        ports: 
            - "3838:3838"
    
    rstudio:
        build: 
            context: .
            dockerfile: rstudio_tcc.dockerfile
        ports:
            - "8787:8787"
        environment:
            - PASSWORD=123
        volumes:
            - .:/home/rstudio

