---
output:
  pdf_document:
    #number_sections: yes
    #toc: yes
    keep_tex: true
    template: template.tex
  word_document:
    toc: yes
    #reference_docx: 'modelo.docx'
    
date: "`r format(Sys.time(), '%d %B, %Y')`"
author: |
  Douglas Braga \\
  Felipe Sales
title: "Optimização Bayesiana"
subtitle: |
  Uma aplicação para otimização de hiperparâmetros de modelos de machine learning.
supervisor: "Orientador"
institution: |
  Escola Nacional de Ciências Estatísticas \\
  Bacharelado em Estatística
degree: "Bacharelado em Estatística"

abstract: "This document provides an introduction to R Markdown, argues for its..."
keywords: "pandoc, r markdown, knitr"
resumo: |
  Segundo a \citeonline{} \citeonline[3.1-3.2]{NBR6028:2003}, o resumo deve ressaltar o
  objetivo, o método, os resultados e as conclusões do documento. A ordem e a extensão
  destes itens dependem do tipo de resumo (informativo ou indicativo) e do
  tratamento que cada item recebe no documento original. O resumo deve ser
  precedido da referência do documento, com exceção do resumo inserido no
  próprio documento. (\ldots) As palavras-chave devem figurar logo abaixo do
  resumo, antecedidas da expressão Palavras-chave:, separadas entre si por
  ponto e finalizadas também por ponto.
chave: latex. abntex. editoração de texto.
agradecimento: |
  O agradecimento principal é direcionado a Youssef Cherem, autor do
  \nameref{formulado-identificacao} (\autopageref{formulado-identificacao}).

  Os agradecimentos especiais são direcionados ao Centro de Pesquisa em
  Arquitetura da Informação\footnote{\url{http://www.cpai.unb.br/}} da Universidade de
  Brasília (CPAI), ao grupo de usuários
  \emph{latex-br}\footnote{\url{http://groups.google.com/group/latex-br}} e aos
  novos voluntários do grupo
  \emph{\abnTeX}\footnote{\url{http://groups.google.com/group/abntex2} e
  \url{http://www.abntex.net.br/}}~que contribuíram e que ainda
  contribuirão para a evolução do abn\TeX.
  
preambulo: |
  Modelo canônico de Relatório Técnico e/ou Científico em conformidade
  com as normas ABNT apresentado à comunidade de usuários \LaTeX.

lot: true
lof: true
fontsize: 11pt
bibliography: bibliography.bibtex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F, fig.pos = 'H')
```

\newpage 

```{r}
download.file("https://cdn-images-1.medium.com/max/1600/1*PhKGj_bZlND8IEfII426wA.png",
              "images/bo.png",quiet = T,mode = 'wb')
```

```{r}
download.file("https://github.com/probml/pmtk3/blob/30d7a1952f3979b16e92dbfa4cd1ce0e402cf7d8/docs/demoOutput/bookDemos/(15)-Gaussian_processes/gprDemoNoiseFree_02.png?raw=true",
              "images/gp.png",quiet = T,mode = 'wb')
```

Este texto tem como base: [@brochu2010tutorial], [@snoek2012practical] e [@ebden2015gaussian]

## Introdução

```{r child='markdown/01-introdução.rmd'}
```

## Metodologia

```{r child='markdown/02-metodologia.rmd'}
```

\newpage 

# Referências